# Generated by Django 5.0 on 2023-12-12 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('map_url', models.URLField()),
                ('img_url', models.URLField()),
                ('location', models.CharField(max_length=200)),
                ('has_sockets', models.BooleanField()),
                ('has_toilet', models.BooleanField()),
                ('has_wifi', models.BooleanField()),
                ('can_take_calls', models.BooleanField()),
                ('seats', models.IntegerField()),
                ('coffee_price', models.FloatField()),
            ],
        ),
    ]
